Expand the list of packages to include most browsers
AdguardTeam/adguardcert pull request #4
Opened 2022-03-31 16:49 UTC by ngorskikh

Also increment version, update the readme and metadata.

2022-03-31 17:01 UTC, sfionov commented on zygisk_module/jni/browsers.inc
> +"com.naver.whale",
"No newline at end of file" ругается

2022-03-31 19:01 UTC, sfionov commented on README.md
> +Chrome (and eventually many other Chromium-based browsers)
Не очень согласуется "eventually" и "recently".

Предлагаю позвать @vbagirov :)

2022-04-01 09:56 UTC, vbagirov requested changes

2022-04-01 09:56 UTC, vbagirov commented on README.md
> +Chrome (and eventually many other Chromium-based browsers)
`Chrome (and subsequently many other Chromium-based browsers) has recently started requiring CT logs for CA certs found in the **System store**.`

2022-04-01 12:08 UTC, sfionov approved these changes

2022-04-01 12:08 UTC, ameshkov approved these changes

2022-04-01 12:13 UTC, merged